version: "3.8"
services:
  database:
    image: "library/mariadb:10.5.9"
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: dict
      MYSQL_USER: dict
      MYSQL_PASSWORD: dict
      MYSQL_DATABASE: dict
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/

  adminer:
    image: "library/adminer:4.8.0"
    ports:
    - 3037:8080
    environment:
      ADMINER_PLUGINS: 'tables-filter tinymce'